import dayjs from 'dayjs';

export const state = () => ({
  program: {
    id: 0,
    title: 'Børnedag i Vejlby-Risskov Hallen, Aarhus',
    date: dayjs('2020-11-21').locale('da').format('D MMMM YYYY'),
    dateDay: dayjs('2020-11-21').locale('da').format('dddd'),
    shows: [
      {
        id: 0,
        announcement: true,
        lineup: false,
        time: '08:30',
        team: 'Dørene åbner for gymnaster og publikum',
        instructors: null,
        lineupImg: null,
      },
      {
        id: 1,
        announcement: true,
        lineup: false,
        time: '10:00',
        team: 'FaneIndmarch',
        instructors: null,
        lineupImg: null,
      },
      {
        id: 2,
        announcement: false,
        lineup: false,
        time: '10:15',
        team: 'Vandel Efterskole',
        instructors: 'Christina, Anna, Thomas, Malte, Rasmus og Simon',
        lineupImg: null,
      },
      {
        id: 3,
        announcement: true,
        lineup: false,
        time: '10:45',
        team: 'Pause',
        instructors: null,
        lineupImg: null,
      },
      {
        id: 4,
        announcement: false,
        lineup: true,
        time: '10:50',
        team: 'ST70 - Pigetons',
        instructors: 'Mette Caroline, Mia Christiane og Lena',
        lineupImg: 'one',
      },
      {
        id: 5,
        announcement: false,
        lineup: true,
        time: '10:58',
        team: 'HEI - Hjortshøj-Egå Idrætsforening - Mixspring fra 5. kl.',
        instructors: 'Katrine, Signe, Helena og Victor',
        lineupImg: 'two',
      },
      {
        id: 6,
        announcement: false,
        lineup: true,
        time: '11:06',
        team: 'ST70 - Supergirls',
        instructors: 'Mia Christiane, Mette Caroline og Lena',
        lineupImg: 'one',
      },
      {
        id: 7,
        announcement: false,
        lineup: true,
        time: '11:12',
        team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Junioraspiranter',
        instructors: 'Mille Olivia, Frida, Alberte og Cecilie',
        lineupImg: 'one',
      },
      {
        id: 8,
        announcement: true,
        lineup: false,
        time: '11:20',
        team: 'Pause',
        instructors: null,
        lineupImg: 'one',
      },
      {
        id: 9,
        announcement: false,
        lineup: false,
        time: '11:30',
        team: 'Himmerlandscentrets Idrætsefterskole',
        instructors: 'Christian, Christian, Jacob, Helene og Heidi',
        lineupImg: 'one',
      },
      {
        id: 10,
        announcement: true,
        lineup: false,
        time: '12:00',
        team: 'Pause',
        instructors: null,
        lineupImg: 'one',
      },
      {
        id: 11,
        announcement: false,
        lineup: true,
        time: '12:05',
        team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Spireholdet',
        instructors: 'Maria, Mathilde, Kaya, Mathilde og Sofie',
        lineupImg: 'one',
      },
      {
        id: 12,
        announcement: false,
        lineup: true,
        time: '12:13',
        team: 'Hinnerup Gymnastiksamvirke - Rytmepiger 3.-6. kl. og Dans og rytmisk gymnastik for piger 4.-8. kl.',
        instructors: 'Cecilie, Sarah, Rosa og Astrid',
        lineupImg: 'one',
      },
      {
        id: 13,
        announcement: false,
        lineup: true,
        time: '12:28',
        team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Mini-aspiranter',
        instructors: 'Mille, Kamille, Alberte og Cecilie',
        lineupImg: 'one',
      },
      {
        id: 14,
        announcement: false,
        lineup: true,
        time: '12:36',
        team: 'Lystrup Idrætsforening - Team Starlight Grand Prix Rytme',
        instructors: 'Caroline, Signe og Sarah',
        lineupImg: 'one',
      },
      {
        id: 15,
        announcement: false,
        lineup: true,
        time: '12:42',
        team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Aspirantholdet',
        instructors: 'Louise, Rikke, Emil, Rasmus, Nikolai, Isabella og Anne',
        lineupImg: 'one',
      },
      {
        id: 16,
        announcement: false,
        lineup: true,
        time: '12:50',
        team: 'Lystrup Idrætsforening - Team Saturn Grand Prix Rytme',
        instructors: 'Freja, Mathilde og Karla',
        lineupImg: 'one',
      },
      {
        id: 17,
        announcement: false,
        lineup: true,
        time: '12:56',
        team: 'VIK - Vejlby Idræts Klub - Acro Konkurrencehold',
        instructors: 'Camilla, Mette, Emma og Christine',
        lineupImg: 'one',
      },
      {
        id: 18,
        announcement: true,
        lineup: false,
        time: '13:04',
        team: 'Pause',
        instructors: null,
        lineupImg: null,
      },
      {
        id: 19,
        announcement: false,
        lineup: false,
        time: '13:14',
        team: 'Brøruphus Efterskole',
        instructors: 'Christina, Anna, Thomas, Malte, Rasmus og Simon',
        lineupImg: null,
      },
      {
        id: 20,
        announcement: true,
        lineup: false,
        time: '13:44',
        team: 'Pause',
        instructors: null,
        lineupImg: null,
      },
      {
        id: 21,
        announcement: false,
        lineup: true,
        time: '13:49',
        team: 'VIK - Vejlby Idræts Klub - Mikropiger 0.-2. kl. og Karateprinsesser 2.-3. kl.',
        instructors: 'Michael, Lene, Sofie, Diana, Hanibal, Mathilde, Anders, Sophia, Victoria og Merete',
        lineupImg: 'one',
      },
      {
        id: 22,
        announcement: false,
        lineup: true,
        time: '14:04',
        team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Opvisningsholdet (Spring og Rytme)',
        instructors: 'Louise, Rikke, Signe, Bine, Anne Luna, Emil, Rasmus, Theodor, Sam og Rasmus',
        lineupImg: 'one',
      },
      {
        id: 23,
        announcement: false,
        lineup: true,
        time: '14:19',
        team: 'BMI - Beder-Malling Idrætsforening - Luftens Helte',
        instructors: 'Christian og Lise',
        lineupImg: 'one',
      },
      {
        id: 24,
        announcement: false,
        lineup: true,
        time: '14:29',
        team: 'VIK - Vejlby Idræts Klub - Tarzan-Jane 5-7 år og Karateprinsesser 2.-5. kl.',
        instructors: 'Emilie, Jacob, Mie, Maja, Mathilde, Caroline og hjælpere',
        lineupImg: 'one',
      },
      {
        id: 25,
        announcement: false,
        lineup: true,
        time: '14:44',
        team: 'BMI - Beder-Malling Idrætsforening - Mix spring',
        instructors: 'Christian, Lucas, Lea, Josephine, Ulrikke og Jørn',
        lineupImg: 'one',
      },
      {
        id: 26,
        announcement: false,
        lineup: true,
        time: '14:59',
        team: 'DGI Østjylland - 10-14holdet',
        instructors: 'Laura, Nina, Phillip, Esben, Jørgen, Line, Charlotte, Karina og Denise',
        lineupImg: 'one',
      },
      {
        id: 27,
        announcement: true,
        lineup: false,
        time: '15:29',
        team: 'Pause',
        instructors: null,
        lineupImg: null,
      },
      {
        id: 28,
        announcement: false,
        lineup: false,
        time: '15:34',
        team: 'Ågård Efterskole',
        instructors: 'Rasmus, Jes, Lise, Maria og Hans',
        lineupImg: null,
      },
      {
        id: 29,
        announcement: true,
        lineup: false,
        time: '16:04',
        team: 'Faneudmarch og tak for i dag',
        instructors: null,
        lineupImg: null,
      },
    ],
  },
});
