import dayjs from 'dayjs';

export const state = () => ({
  program: [
    {
      id: 0,
      title: 'Børnedag i Vejlby-Risskov Hallen, Aarhus',
      date: dayjs('2020-11-21').locale('da').format('D MMMM YYYY'),
      dateDay: dayjs('2020-11-21').locale('da').format('dddd'),
      shows: [
        {
          id: 0,
          announcement: true,
          lineup: false,
          time: '08:30',
          team: 'Dørene åbner for gymnaster og publikum',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 1,
          announcement: true,
          lineup: false,
          time: '10:00',
          team: 'FaneIndmarch',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 2,
          announcement: false,
          lineup: false,
          time: '10:15',
          team: 'Vandel Efterskole',
          instructors: 'Christina, Anna, Thomas, Malte, Rasmus og Simon',
          lineupImg: null,
        },
        {
          id: 3,
          announcement: true,
          lineup: false,
          time: '10:45',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 4,
          announcement: false,
          lineup: true,
          time: '10:50',
          team: 'ST70 - Pigetons',
          instructors: 'Mette Caroline, Mia Christiane og Lena',
          lineupImg: 'one',
        },
        {
          id: 5,
          announcement: false,
          lineup: true,
          time: '10:58',
          team: 'HEI - Hjortshøj-Egå Idrætsforening - Mixspring fra 5. kl.',
          instructors: 'Katrine, Signe, Helena og Victor',
          lineupImg: 'two',
        },
        {
          id: 6,
          announcement: false,
          lineup: true,
          time: '11:06',
          team: 'ST70 - Supergirls',
          instructors: 'Mia Christiane, Mette Caroline og Lena',
          lineupImg: 'one',
        },
        {
          id: 7,
          announcement: false,
          lineup: true,
          time: '11:12',
          team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Junioraspiranter',
          instructors: 'Mille Olivia, Frida, Alberte og Cecilie',
          lineupImg: 'one',
        },
        {
          id: 8,
          announcement: true,
          lineup: false,
          time: '11:20',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 9,
          announcement: false,
          lineup: false,
          time: '11:30',
          team: 'Himmerlandscentrets Idrætsefterskole',
          instructors: 'Christian, Christian, Jacob, Helene og Heidi',
          lineupImg: null,
        },
        {
          id: 10,
          announcement: true,
          lineup: false,
          time: '12:00',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 11,
          announcement: false,
          lineup: true,
          time: '12:05',
          team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Spireholdet',
          instructors: 'Maria, Mathilde, Kaya, Mathilde og Sofie',
          lineupImg: 'one',
        },
        {
          id: 12,
          announcement: false,
          lineup: true,
          time: '12:13',
          team: 'Hinnerup Gymnastiksamvirke - Rytmepiger 3.-6. kl. og Dans og rytmisk gymnastik for piger 4.-8. kl.',
          instructors: 'Cecilie, Sarah, Rosa og Astrid',
          lineupImg: 'one',
        },
        {
          id: 13,
          announcement: false,
          lineup: true,
          time: '12:28',
          team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Mini-aspiranter',
          instructors: 'Mille, Kamille, Alberte og Cecilie',
          lineupImg: 'one',
        },
        {
          id: 14,
          announcement: false,
          lineup: true,
          time: '12:36',
          team: 'Lystrup Idrætsforening - Team Starlight Grand Prix Rytme',
          instructors: 'Caroline, Signe og Sarah',
          lineupImg: 'one',
        },
        {
          id: 15,
          announcement: false,
          lineup: true,
          time: '12:42',
          team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Aspirantholdet',
          instructors: 'Louise, Rikke, Emil, Rasmus, Nikolai, Isabella og Anne',
          lineupImg: 'one',
        },
        {
          id: 16,
          announcement: false,
          lineup: true,
          time: '12:50',
          team: 'Lystrup Idrætsforening - Team Saturn Grand Prix Rytme',
          instructors: 'Freja, Mathilde og Karla',
          lineupImg: 'one',
        },
        {
          id: 17,
          announcement: false,
          lineup: true,
          time: '12:56',
          team: 'VIK - Vejlby Idræts Klub - Acro Konkurrencehold',
          instructors: 'Camilla, Mette, Emma og Christine',
          lineupImg: 'one',
        },
        {
          id: 18,
          announcement: true,
          lineup: false,
          time: '13:04',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 19,
          announcement: false,
          lineup: false,
          time: '13:14',
          team: 'Brøruphus Efterskole',
          instructors: 'Christina, Anna, Thomas, Malte, Rasmus og Simon',
          lineupImg: null,
        },
        {
          id: 20,
          announcement: true,
          lineup: false,
          time: '13:44',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 21,
          announcement: false,
          lineup: true,
          time: '13:49',
          team: 'VIK - Vejlby Idræts Klub - Mikropiger 0.-2. kl. og Karateprinsesser 2.-3. kl.',
          instructors: 'Michael, Lene, Sofie, Diana, Hanibal, Mathilde, Anders, Sophia, Victoria og Merete',
          lineupImg: 'one',
        },
        {
          id: 22,
          announcement: false,
          lineup: true,
          time: '14:04',
          team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Opvisningsholdet (Spring og Rytme)',
          instructors: 'Louise, Rikke, Signe, Bine, Anne Luna, Emil, Rasmus, Theodor, Sam og Rasmus',
          lineupImg: 'one',
        },
        {
          id: 23,
          announcement: false,
          lineup: true,
          time: '14:19',
          team: 'BMI - Beder-Malling Idrætsforening - Luftens Helte',
          instructors: 'Christian og Lise',
          lineupImg: 'one',
        },
        {
          id: 24,
          announcement: false,
          lineup: true,
          time: '14:29',
          team: 'VIK - Vejlby Idræts Klub - Tarzan-Jane 5-7 år og Karateprinsesser 2.-5. kl.',
          instructors: 'Emilie, Jacob, Mie, Maja, Mathilde, Caroline og hjælpere',
          lineupImg: 'one',
        },
        {
          id: 25,
          announcement: false,
          lineup: true,
          time: '14:44',
          team: 'BMI - Beder-Malling Idrætsforening - Mix spring',
          instructors: 'Christian, Lucas, Lea, Josephine, Ulrikke og Jørn',
          lineupImg: 'one',
        },
        {
          id: 26,
          announcement: false,
          lineup: true,
          time: '14:59',
          team: 'DGI Østjylland - 10-14holdet',
          instructors: 'Laura, Nina, Phillip, Esben, Jørgen, Line, Charlotte, Karina og Denise',
          lineupImg: 'one',
        },
        {
          id: 27,
          announcement: true,
          lineup: false,
          time: '15:29',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 28,
          announcement: false,
          lineup: false,
          time: '15:34',
          team: 'Ågård Efterskole',
          instructors: 'Rasmus, Jes, Lise, Maria og Hans',
          lineupImg: null,
        },
        {
          id: 29,
          announcement: true,
          lineup: false,
          time: '16:04',
          team: 'Faneudmarch og tak for i dag',
          instructors: null,
          lineupImg: null,
        },
      ],
    },
    {
      id: 1,
      title: 'Børnedag i Vejlby-Risskov Hallen, Aarhus',
      date: dayjs('2020-11-22').locale('da').format('D MMMM YYYY'),
      dateDay: dayjs('2020-11-22').locale('da').format('dddd'),
      shows: [
        {
          id: 0,
          announcement: true,
          lineup: false,
          time: '08:30',
          team: 'Dørene åbner for gymnaster og publikum',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 1,
          announcement: true,
          lineup: false,
          time: '09:30',
          team: 'FaneIndmarch',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 2,
          announcement: false,
          lineup: false,
          time: '09:45',
          team: 'Vojens Gymnastik- & Idrætsefterskole',
          instructors: 'Kristian, Anne-Katrine, John, Jakob og Charlotte',
          lineupImg: null,
        },
        {
          id: 3,
          announcement: true,
          lineup: false,
          time: '10:15',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 4,
          announcement: false,
          lineup: true,
          time: '10:20',
          team: 'Aabyhøj IF - Power Girls',
          instructors: 'Nikoline og Nikoline',
          lineupImg: 'one',
        },
        {
          id: 5,
          announcement: false,
          lineup: true,
          time: '10:28',
          team: 'Elise Puls - Tons for drenge og piger 6-10 år, Gymnastik-piger 6-7 år og Spring og Dans for piger 7-10 år.',
          instructors: 'Frederik, Helena, Simone, Monica, Rasmus, Anne, Mette og Anita',
          lineupImg: 'two',
        },
        {
          id: 6,
          announcement: false,
          lineup: true,
          time: '10:43',
          team: 'Aabyhøj IF - Springbomberne',
          instructors: 'Karen, Maria, Clara, Mille og Sara',
          lineupImg: 'one',
        },
        {
          id: 7,
          announcement: false,
          lineup: true,
          time: '10:51',
          team: 'Stavtrup Idrætsforening - 4.-6. kl. Spring',
          instructors: 'Katrine',
          lineupImg: 'one',
        },
        {
          id: 8,
          announcement: false,
          lineup: true,
          time: '10:59',
          team: 'Aabyhøj IF - PowerPuff piger 5 år - 1. kl.',
          instructors: 'Pia, Alexandra og Victoria',
          lineupImg: 'one',
        },
        {
          id: 9,
          announcement: false,
          lineup: true,
          time: '11:05',
          team: 'AGF Gymnastik - Tons og Tøser 1 og Tons og Tøser 2',
          instructors: 'Sabine, Camilla, Frida, Marie, Clara og Cecilie',
          lineupImg: 'one',
        },
        {
          id: 10,
          announcement: true,
          lineup: true,
          time: '11:21',
          team: 'Stavtrup Idrætsforening - 1. kl. spring og rytme',
          instructors: 'Linda',
          lineupImg: 'one',
        },
        {
          id: 11,
          announcement: false,
          lineup: true,
          time: '11:29',
          team: 'Brabrand Idrætsforening - Mixspring 4.-6. kl., let øvet',
          instructors: 'Nikoline, Fie, Clara, Ane og Alberte',
          lineupImg: 'one',
        },
        {
          id: 12,
          announcement: false,
          lineup: true,
          time: '11:44',
          team: 'AGF Gymnastik - Saltoteam 0.-3. kl.',
          instructors: 'Karen, Noa, Stella og Sofie',
          lineupImg: 'one',
        },
        {
          id: 13,
          announcement: false,
          lineup: true,
          time: '11:54',
          team: 'AIA-Tranbjerg - Spring let øvet',
          instructors: 'Emma, Anne og Katharina',
          lineupImg: 'one',
        },
        {
          id: 14,
          announcement: true,
          lineup: false,
          time: '12:02',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 15,
          announcement: false,
          lineup: true,
          time: '12:17',
          team: 'AGF Gymnastik - Tons og Dans',
          instructors: 'Sabine, Pernille og Camilla',
          lineupImg: 'one',
        },
        {
          id: 16,
          announcement: false,
          lineup: false,
          time: '12:23',
          team: 'DGI Østjylland - JUNIORholdet',
          instructors: 'Kresten, Mikkel, Thomas, Line, Maja og Trine',
          lineupImg: null,
        },
        {
          id: 17,
          announcement: false,
          lineup: true,
          time: '12:56',
          team: 'VIK - Vejlby Idræts Klub - Acro Konkurrencehold',
          instructors: 'Camilla, Mette, Emma og Christine',
          lineupImg: 'one',
        },
        {
          id: 18,
          announcement: false,
          lineup: true,
          time: '12:53',
          team: 'Hørning Puls - MicroSpring 0.-1. kl.',
          instructors: 'Elsebeth',
          lineupImg: 'two',
        },
        {
          id: 19,
          announcement: false,
          lineup: true,
          time: '13:01',
          team: 'Hinnerup Gymnastiksamvirke - Springpiger 2.-4. kl. og Springdrenge 3.-5. kl.',
          instructors: 'Heidi, Helle, Lone, Oliver, Victor, Karla, Rebekka, Thea, Niels, Martin, Carsten, Simon og Jesper',
          lineupImg: 'one',
        },
        {
          id: 20,
          announcement: true,
          lineup: false,
          time: '13:16',
          team: 'Hørning Puls - Showdance fra 2. kl.',
          instructors: 'Frezenia og Sofie',
          lineupImg: null,
        },
        {
          id: 21,
          announcement: false,
          lineup: true,
          time: '13:22',
          team: 'Højbjerg Gymnastikforening - Piger spring 3.-5. kl.',
          instructors: 'Line, Victoria, Luna, William og Celine',
          lineupImg: 'one',
        },
        {
          id: 22,
          announcement: false,
          lineup: true,
          time: '13:30',
          team: 'Hørning Puls - MicroSpring 0.-2. kl.',
          instructors: 'Sanne',
          lineupImg: 'one',
        },
        {
          id: 23,
          announcement: false,
          lineup: true,
          time: '13:38',
          team: 'Hinnerup Gymnastiksamvirke - Springpiger 4.-5. kl.',
          instructors: 'Jim, Sanne, Signe, Holger, Morten, Oliver, Sander og Victor',
          lineupImg: 'one',
        },
        {
          id: 24,
          announcement: false,
          lineup: true,
          time: '13:53',
          team: 'Hørning Puls - MixSpring 3.-5. kl.',
          instructors: 'Hella, Pernille og Britt',
          lineupImg: 'one',
        },
        {
          id: 25,
          announcement: false,
          lineup: true,
          time: '14:01',
          team: 'AIA-Tranbjerg - Spring Aspiranterne',
          instructors: 'Tina og Laura',
          lineupImg: 'one',
        },
        {
          id: 26,
          announcement: false,
          lineup: true,
          time: '14:09',
          team: 'Højbjerg Gymnastikforening - Piger spring 1.-2. kl.',
          instructors: 'Celine, Camille, Frederikke og Vala',
          lineupImg: 'one',
        },
        {
          id: 27,
          announcement: false,
          lineup: true,
          time: '14:17',
          team: 'Hørning Puls - MixSpring 3.-5. kl. hold 1',
          instructors: 'Mikkel og Mette',
          lineupImg: 'one',
        },
        {
          id: 28,
          announcement: true,
          lineup: false,
          time: '14:25',
          team: 'Pause',
          instructors: null,
          lineupImg: null,
        },
        {
          id: 29,
          announcement: false,
          lineup: false,
          time: '14:40',
          team: 'DGI Østjylland - ASPIRANTholdet',
          instructors: 'Rikke, Karoline, Anette, Oliver og Casper',
          lineupImg: null,
        },
        {
          id: 30,
          announcement: false,
          lineup: true,
          time: '15:10',
          team: 'Højbjerg Gymnastikforening - Hiphop og Showdance 4.-5. kl.',
          instructors: 'Nana og Regitze',
          lineupImg: 'one',
        },
        {
          id: 31,
          announcement: false,
          lineup: true,
          time: '15:16',
          team: 'Viby Idrætsforening - Viby Aspirantspring',
          instructors: 'Martin, Victoria, Julie, Julius og Camilla',
          lineupImg: 'one',
        },
        {
          id: 32,
          announcement: false,
          lineup: false,
          time: '15:31',
          team: 'Hammerum Efterskole',
          instructors: 'Anne, Christina, Jeppe og Niclas',
          lineupImg: null,
        },
        {
          id: 33,
          announcement: true,
          lineup: false,
          time: '16:01',
          team: 'Faneudmarch og tak for i dag',
          instructors: null,
          lineupImg: null,
        },
      ],
    },
  ],
});
