export const state = () => ({
  program: [
    {
      id: 0,
      announcement: true,
      lineup: false,
      time: '08:30',
      team: 'Dørene åbner for gymnaster og publikum',
      instructors: '',
    },
    {
      id: 1,
      announcement: true,
      lineup: false,
      time: '10:00',
      team: 'FaneIndmarch',
      instructors: '',
    },
    {
      id: 2,
      announcement: false,
      lineup: false,
      time: '10:15',
      team: 'Vandel Efterskole',
      instructors: 'Christina, Anna, Thomas, Malte, Rasmus og Simon',
    },
    {
      id: 3,
      announcement: true,
      lineup: false,
      time: '10:45',
      team: 'Pause',
      instructors: '',
    },
    {
      id: 4,
      announcement: false,
      lineup: true,
      time: '10:50',
      team: 'ST70 - Pigetons',
      instructors: 'Mette Caroline, Mia Christiane og Lena',
    },
    {
      id: 5,
      announcement: false,
      lineup: true,
      time: '10:58',
      team: 'HEI - Hjortshøj-Egå Idrætsforening - Mixspring fra 5. kl.',
      instructors: 'Katrine, Signe, Helena og Victor',
    },
    {
      id: 6,
      announcement: false,
      lineup: true,
      time: '11:06',
      team: 'ST70 - Supergirls',
      instructors: 'Mia Christiane, Mette Caroline og Lena',
    },
    {
      id: 7,
      announcement: false,
      lineup: true,
      time: '11:12',
      team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Junioraspiranter',
      instructors: 'Mille Olivia, Frida, Alberte og Cecilie',
    },
    {
      id: 8,
      announcement: true,
      lineup: false,
      time: '11:20',
      team: 'Pause',
      instructors: '',
    },
    {
      id: 9,
      announcement: false,
      lineup: false,
      time: '11:30',
      team: 'Himmerlandscentrets Idrætsefterskole',
      instructors: 'Christian, Christian, Jacob, Helene og Heidi',
    },
    {
      id: 10,
      announcement: true,
      lineup: false,
      time: '12:00',
      team: 'Pause',
      instructors: '',
    },
    {
      id: 11,
      announcement: false,
      lineup: true,
      time: '12:05',
      team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Spireholdet',
      instructors: 'Maria, Mathilde, Kaya, Mathilde og Sofie',
    },
    {
      id: 12,
      announcement: false,
      lineup: true,
      time: '12:13',
      team: 'Hinnerup Gymnastiksamvirke - Rytmepiger 3.-6. kl. og Dans og rytmisk gymnastik for piger 4.-8. kl.',
      instructors: 'Cecilie, Sarah, Rosa og Astrid',
    },
    {
      id: 13,
      announcement: false,
      lineup: true,
      time: '12:28',
      team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Mini-aspiranter',
      instructors: 'Mille, Kamille, Alberte og Cecilie',
    },
    {
      id: 14,
      announcement: false,
      lineup: true,
      time: '12:36',
      team: 'Lystrup Idrætsforening - Team Starlight Grand Prix Rytme',
      instructors: 'Caroline, Signe og Sarah',
    },
    {
      id: 15,
      announcement: false,
      lineup: true,
      time: '12:42',
      team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Aspirantholdet',
      instructors: 'Louise, Rikke, Emil, Rasmus, Nikolai, Isabella og Anne',
    },
    {
      id: 16,
      announcement: false,
      lineup: true,
      time: '12:50',
      team: 'Lystrup Idrætsforening - Team Saturn Grand Prix Rytme',
      instructors: 'Freja, Mathilde og Karla',
    },
    {
      id: 17,
      announcement: false,
      lineup: true,
      time: '12:56',
      team: 'VIK - Vejlby Idræts Klub - Acro Konkurrencehold',
      instructors: 'Camilla, Mette, Emma og Christine',
    },
    {
      id: 18,
      announcement: true,
      lineup: false,
      time: '13:04',
      team: 'Pause',
      instructors: '',
    },
    {
      id: 19,
      announcement: false,
      lineup: false,
      time: '13:14',
      team: 'Brøruphus Efterskole',
      instructors: 'Christina, Anna, Thomas, Malte, Rasmus og Simon',
    },
    {
      id: 20,
      announcement: true,
      lineup: false,
      time: '13:44',
      team: 'Pause',
      instructors: '',
    },
    {
      id: 21,
      announcement: false,
      lineup: true,
      time: '13:49',
      team: 'VIK - Vejlby Idræts Klub - Mikropiger 0.-2. kl. og Karateprinsesser 2.-3. kl.',
      instructors: 'Michael, Lene, Sofie, Diana, Hanibal, Mathilde, Anders, Sophia, Victoria og Merete',
    },
    {
      id: 22,
      announcement: false,
      lineup: true,
      time: '14:04',
      team: 'HEI - Hjortshøj-Egå Idrætsforening - Aarhus ShowTeam Opvisningsholdet (Spring og Rytme)',
      instructors: 'Louise, Rikke, Signe, Bine, Anne Luna, Emil, Rasmus, Theodor, Sam og Rasmus',
    },
    {
      id: 23,
      announcement: false,
      lineup: true,
      time: '14:19',
      team: 'BMI - Beder-Malling Idrætsforening - Luftens Helte',
      instructors: 'Christian og Lise',
    },
    {
      id: 24,
      announcement: false,
      lineup: true,
      time: '14:29',
      team: 'VIK - Vejlby Idræts Klub - Tarzan-Jane 5-7 år og Karateprinsesser 2.-5. kl.',
      instructors: 'Emilie, Jacob, Mie, Maja, Mathilde, Caroline og hjælpere',
    },
    {
      id: 25,
      announcement: false,
      lineup: true,
      time: '14:44',
      team: 'BMI - Beder-Malling Idrætsforening - Mix spring',
      instructors: 'Christian, Lucas, Lea, Josephine, Ulrikke og Jørn',
    },
    {
      id: 26,
      announcement: false,
      lineup: true,
      time: '14:59',
      team: 'DGI Østjylland - 10-14holdet',
      instructors: 'Laura, Nina, Phillip, Esben, Jørgen, Line, Charlotte, Karina og Denise',
    },
    {
      id: 27,
      announcement: true,
      lineup: false,
      time: '15:29',
      team: 'Pause',
      instructors: '',
    },
    {
      id: 28,
      announcement: false,
      lineup: false,
      time: '15:34',
      team: 'Ågård Efterskole',
      instructors: 'Rasmus, Jes, Lise, Maria og Hans',
    },
    {
      id: 29,
      announcement: true,
      lineup: false,
      time: '16:04',
      team: 'Faneudmarch og tak for i dag',
      instructors: '',
    },
  ],
});
